{% set name = "suitcase-csv" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21a24b763de39a621cb79a359954c7fff1956f5313870834bb3a0d895c382c29

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - event-model >=1.8.0
    - pandas
    - python
    - suitcase-utils

test:
  imports:
    - suitcase.csv

about:
  home: https://nsls-ii.github.io/suitcase
  license: BSD (3-clause)
  license_family: BSD
  license_file: 
  summary: Export bluesky documents to CSV
  doc_url: https://nsls-ii.github.io/suitcase
  dev_url: https://github.com/NSLS-II/suitcase-csv

extra:
  recipe-maintainers:
    - NSLS-II
